# Generated by Django 6.0.5 on 2026-05-19 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_codigo', models.CharField(max_length=10, verbose_name='Codigo del Ítem')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o Justificación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_PROCESO', 'En Proceso de Compra'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
