# Generated by Django 6.0.5 on 2026-05-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='item_codigo',
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, verbose_name='Código del Ítem')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción/Justificación')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudcompra')),
            ],
        ),
    ]
